##load libraries
library(shiny)
library(shinyjs)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(rgeos)
library(rgdal)
library(sp)
library(raster)
library(scales)
library(extrafont)
library(fontcm)
library(leaflet)
library(leaflet.esri)
library(knitr)
library(lubridate)
library(data.table)
library(zoo)
library(rhandsontable)
library(RColorBrewer)
library(reshape)
library(geosphere)
library(maptools)
library(maps)
library(rmarkdown)
library(tinytex)
library(igraph)
library(htmlwidgets)
library(webshot)
library(rlist)
library(ellipsis)
library(stringi)
library(RODBC)
library(DBI)
library(sqldf)

if (file.exists('./scripts/creds.R') == TRUE){
  library(shinymanager, lib.loc = "/net/home5/lcrowe/R/x86_64-redhat-linux-gnu-library/3.6/")

  }