#load libraries
# library(shiny)
# library(shinyjs)
# library(shinydashboard)
# library(dplyr)
# library(ggplot2)
# library(rgeos)
# library(rgdal)
# library(sf)
# library(sp)
# library(raster)
# library(scales)
# library(extrafont)
# library(fontcm)
# library(leaflet)
# library(leaflet.esri)
# library(knitr)
# library(lubridate)
# library(data.table)
# library(zoo)
# library(rhandsontable)
# library(RColorBrewer)
# library(reshape)
# library(geosphere)
# library(maptools)
# library(maps)
# library(rmarkdown)
# library(tinytex)
# library(igraph)
# library(htmlwidgets)
# library(webshot)
# library(rlist)
# library(ellipsis)
# library(stringi)
# library(DBI)
# library(sqldf)
# library(shinymanager)
# library(ssh)
# library(ROracle)

require(ROracle)
require(ssh)
require(shiny)
require(shinyjs)
require(shinydashboard)
require(dplyr)
require(ggplot2)
require(rgeos)
require(rgdal)
require(sf)
require(sp)
require(raster)
require(scales)
require(extrafont)
require(fontcm)
require(leaflet)
require(leaflet.esri)
require(knitr)
require(lubridate)
require(data.table)
require(zoo)
require(rhandsontable)
require(RColorBrewer)
require(reshape)
require(geosphere)
require(maptools)
require(maps)
require(rmarkdown)
require(tinytex)
require(igraph)
require(htmlwidgets)
require(webshot)
require(rlist)
require(ellipsis)
require(stringi)
require(DBI)
require(sqldf)
require(shinymanager)
